In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from IPython.display import display, Markdown
import pandas as pd
import time
from rag_flow import RAGFlow

/Users/vilya/Desktop/capstone_project/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-10-05 20:03:05,406 | INFO | No device provided, using mps
2026-10-05 20:03:05,545 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-10-05 20:03:05,546 | INFO | No modules.json found for cross-encoder/ms-marco-MiniLM-L6-v2, initializing a new CrossEncoder model.
2026-10-05 20:03:05,635 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-05 20:03:05,728 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-05 20:03:05,826 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-10-05 20:03:05,921 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-05 20:03:06,016 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 22869.71it/s]
2026-10-05 20:03:06,169 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-05 20:03:06,264 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-05 20:03:06,359 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

In [2]:
def load_model():
    model_name = "Qwen/Qwen3-8B"
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype="auto",
        device_map="auto",
        local_files_only=True #swith it off to download from hugging face if you don't have it locally
    )
    tokenizer = AutoTokenizer.from_pretrained(model_name, local_files_only=True)
    return {"model": model, "tokenizer": tokenizer}

In [3]:
model_and_tokenizer = load_model()
model = model_and_tokenizer["model"]
tokenizer = model_and_tokenizer["tokenizer"]

Loading weights: 100%|██████████| 399/399 [00:01<00:00, 313.62it/s]

In [4]:
params = {
    "model": model,
    "tokenizer": tokenizer,
    "web_query_max_new_t": 50,
    "titles_limit": 5,
    "top_k_titles": 5,
    "chunk_size": 200,
    "chunk_overlap_fraction": 0.2,
    "top_k_chunks": 5,
    "answer_max_new_t": 500
}


rag = RAGFlow(params)

#answer = rag.run("How does retrieval-augmented generation reduce hallucinations in large language models??")

## Evaluation
### System level:
- Token usage per prompt.
- End-to-End Latency
- Context recall (relevant answers / (relevant answers + irrelevant answers). To determine whether an answer is relevant, I will use a threshold of similarity between the actual answer and the correct answer. For example, the cosine similarity is 0.9 then the answer is marked relevant.
- Context precision (relevant answers / total answers)
- Faithfulness (Is the answer strictly true to the retrieved context?" (Checks for hallucination) I am going to use RAGAS library ( if I have no issues configuring it and a LLM-as-judge)
### Retrieval level
- Context precision/ recall @ k
- Mean reciprocal rank (MRR)
- Normalized Discounted Cumulative Gain (NDCG)  how well top-k is sorted

## To do:
- generate ground truth
- test and record the results
- download 1 -2 more models and test the same flow with them. Chose the one that performed best
- With best model, fine-tune the system:
    - test different numbers of searched titles
    - test different number of downloaded articles
    - try different chunk sizes
    - try different number of top k in the chunk ranker
    - try a set of promot augmentation.

In [5]:
sys_evaluation_df = {
    "mean_latency": "",
    "mean_token_usage":"",
    "context_recall":"",
    "context_precision":"",
    "mean_faithfulness":""
}

In [6]:
golden_df = pd.read_csv("golden_dataset.csv")

In [7]:
results = []

for _, row in golden_df.iterrows():
    golden_id = row["golden_id"]
    question = row["question"]
    start = time.perf_counter()
    answer = rag.run(question)
    latency = time.perf_counter() - start
    results.append({
        "golden_id": golden_id,
        "answer": answer,
        "latency": latency
    })

evaluation_df = pd.DataFrame(results)
evaluation_df.to_csv("system_eval_results.csv")

2026-10-05 20:03:10,847 | INFO | user prompt: How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?, web query: confidence supervision token reduction model efficiency
2026-10-05 20:03:22,905 | WARNING | arXiv timeout/no results for query: confidence supervision token reduction model efficiency
2026-10-05 20:03:23,897 | INFO | user prompt: How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?, web query: confidence supervision token reduction model efficiency
2026-10-05 20:03:23,898 | INFO | Retry query: confidence supervision token reduction model efficiency
2026-10-05 20:03:35,355 | WARNING | arXiv timeout/no results for query: confidence supervision token reduction model efficiency
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.42it/s]
2026-10-05 20:03:35,471 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-05 20:03:36,532 | INFO | user prompt: How do authors minimize queries, achieve optimal tgt alignment, post‑process, prompting in black‑box generative AI?, web query: black box generative AI alignment
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]
Batches: 100%|██████████| 13/13 [00:01<00:00, 11.13it/s]
2026-10-05 20:03:44,016 | INFO | Answer generation input tokens: 1788
2026-10-05 20:04:02,084 | INFO | user prompt: How does static compact doc alone affect issue resolution in real repos vs. source present?, web query: static doc resolution real repos source presence
2026-10-05 20:04:13,538 | WARNING | arXiv timeout/no results for query: static doc resolution real repos source presence
2026-10-05 20:04:14,746 | INFO | user prompt: How does static compact doc alone affect issue resolution in real repos vs. source present?, web query: static documentation impact on issue resolution in software repositories
2026-10-05 20:04:14,746 | INFO | Retry query: static documentation impact on issue resolution in software repositories
2026-10-05 20:04:26,166 | WARNING | arXiv timeout/no results for query: static documentation impact on issue resolution in software repositories
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]
2026-10-05 20:04:26,302 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-05 20:04:27,403 | INFO | user prompt: How does OC‑GS refine angles, keep axis, boostPSNR amid uneven rotation, dropped frames, sparse caps?, web query: angle refinement rotation stability PSNR enhancement
2026-10-05 20:04:38,808 | WARNING | arXiv timeout/no results for query: angle refinement rotation stability PSNR enhancement
2026-10-05 20:04:40,007 | INFO | user prompt: How does OC‑GS refine angles, keep axis, boostPSNR amid uneven rotation, dropped frames, sparse caps?, web query: angle refinement stability PSNR improvement under rotation uncertainty
2026-10-05 20:04:40,007 | INFO | Retry query: angle refinement stability PSNR improvement under rotation uncertainty
2026-10-05 20:04:51,474 | WARNING | arXiv timeout/no results for query: angle refinement stability PSNR improvement under rotation uncertainty
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.72it/s]
2026-10-05 20:04:51,590 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-05 20:04:52,503 | INFO | user prompt: How do teachers adapt conv. AI use, balancing repair, differentiation, translation, tech, learner, instr. tensions?, web query: AI adaptation instructional tensions
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
Batches: 100%|██████████| 5/5 [00:00<00:00, 12.21it/s]
2026-10-05 20:04:56,681 | INFO | Answer generation input tokens: 1776
2026-10-05 20:05:09,979 | INFO | user prompt: How does DeepEdu‑v1’s long‑context engine yield TTFT speedup over vLLM in Vietnam AI tutoring?, web query: long context engine TTFT speedup AI tutoring
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]
Batches: 100%|██████████| 4/4 [00:00<00:00, 13.45it/s]
2026-10-05 20:05:12,144 | INFO | Answer generation input tokens: 1990
2026-10-05 20:05:26,487 | INFO | user prompt: Imagine 30 LLMs on a disjunctive task; how does scaling improve accuracy?, web query: LLM scaling disjunctive task accuracy
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.05it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.64it/s]
2026-10-05 20:05:28,633 | INFO | Answer generation input tokens: 2676
2026-10-05 20:05:50,229 | INFO | user prompt: Illustrate how flow‑matching derives neural representational dissimilarity to quantify response distribution differences., web query: flow matching neural representation dissimilarity response distribution
Batches: 100%|██████████| 1/1 [00:00<00:00, 28.17it/s]
Batches: 100%|██████████| 4/4 [00:00<00:00, 12.29it/s]
2026-10-05 20:05:55,091 | INFO | Answer generation input tokens: 1856
2026-10-05 20:06:17,003 | INFO | user prompt: If conflict detection accuracy is 98.6%, what percent of inputs does Touchstone elevate?, web query: Touchstone conflict detection accuracy inputs
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 14.39it/s]
2026-10-05 20:06:18,792 | INFO | Answer generation input tokens: 1915
2026-10-05 20:06:26,895 | INFO | user prompt: Explain RVA's raw‑supervision weight assignment appearance reliab., degr. risk, geom. util., and reactivating suppressed frames., web query: raw supervision weight assignment reliability degradation geometric utility reactivation
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 13.88it/s]
2026-10-05 20:06:29,910 | INFO | Answer generation input tokens: 1899
2026-10-05 20:06:45,925 | INFO | user prompt: Compare LLM performance gaps between Haitian Creole and French across cultural awareness dimensions., web query: LLM cultural awareness Haitian Creole French comparison
2026-10-05 20:06:57,345 | WARNING | arXiv timeout/no results for query: LLM cultural awareness Haitian Creole French comparison
2026-10-05 20:06:58,866 | INFO | user prompt: Compare LLM performance gaps between Haitian Creole and French across cultural awareness dimensions., web query: LLM cross-lingual performance cultural awareness Haitian Creole French
2026-10-05 20:06:58,867 | INFO | Retry query: LLM cross-lingual performance cultural awareness Haitian Creole French
2026-10-05 20:07:10,350 | WARNING | arXiv timeout/no results for query: LLM cross-lingual performance cultural awareness Haitian Creole French
Batches: 100%|██████████| 1/1 [00:00<00:00, 51.19it/s]
2026-10-05 20:07:10,465 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-05 20:07:11,628 | INFO | user prompt: How do prompt‑minimization techniques reduce inference latency in LLMs?, web query: prompt minimization inference latency LLMs
Batches: 100%|██████████| 1/1 [00:00<00:00, 22.33it/s]
Batches: 100%|██████████| 11/11 [00:00<00:00, 11.51it/s]
2026-10-05 20:07:16,167 | INFO | Answer generation input tokens: 1905
2026-10-05 20:07:27,733 | INFO | user prompt: Describe the types of uncertainty outputs and how they support selective prediction., web query: Uncertainty quantification selective prediction
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.59it/s]
Batches: 100%|██████████| 25/25 [00:02<00:00, 11.48it/s]
2026-10-05 20:07:39,903 | INFO | Answer generation input tokens: 2004
2026-10-05 20:07:57,885 | INFO | user prompt: How do generative AI's epistemic sites, governing logics, mechanisms reshape cultural infrastructures via indexicality shift?, web query: generative AI epistemic sites indexicality shift cultural infrastructure
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 58.07it/s]
2026-10-05 20:08:00,750 | INFO | Answer generation input tokens: 1770
2026-10-05 20:08:25,106 | INFO | user prompt: Which game envs are in Kaggle Game Arena, and what info types do they cover?, web query: kaggle game arena environments information types
2026-10-05 20:08:36,664 | WARNING | arXiv timeout/no results for query: kaggle game arena environments information types
2026-10-05 20:08:37,783 | INFO | user prompt: Which game envs are in Kaggle Game Arena, and what info types do they cover?, web query: kaggle game arena environments information types
2026-10-05 20:08:37,783 | INFO | Retry query: kaggle game arena environments information types
2026-10-05 20:08:49,246 | WARNING | arXiv timeout/no results for query: kaggle game arena environments information types
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.93it/s]
2026-10-05 20:08:49,379 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-05 20:08:50,539 | INFO | user prompt: Which LLM preferences (price, quality, brand) does PriceBench recover from booking choices?, web query: LLM preferences booking choices PriceBench
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 14.27it/s]
2026-10-05 20:08:52,843 | INFO | Answer generation input tokens: 1885
2026-10-05 20:09:01,625 | INFO | user prompt: Contrast federated learning with local models and UA‑FedAvg vs FedAvg in infant movement analysis., web query: federated learning local models infant movement analysis
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 10.90it/s]
2026-10-05 20:09:03,442 | INFO | Answer generation input tokens: 1711
2026-10-05 20:09:21,539 | INFO | user prompt: How does SeLATM's segment‑level generation and agentic feedback cut LLM resources yet preserve topic modeling?, web query: segment level generation agentic feedback topic modeling
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.82it/s]
2026-10-05 20:09:27,016 | INFO | Answer generation input tokens: 1939
2026-10-05 20:09:43,310 | INFO | user prompt: Which two corruption‑detection signals are compared, and which ds are used in FL?, web query: corruption detection signals federated learning datasets
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.52it/s]
2026-10-05 20:09:45,578 | INFO | Answer generation input tokens: 1859
2026-10-05 20:09:54,596 | INFO | user prompt: How does LoRA SFT alter correct‑image accuracy, visual‑benefit events, and image sensitivity in Qwen2.5‑VL‑3B post‑training?, web query: LoRA fine-tuning visual accuracy image sensitivity
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.07it/s]
2026-10-05 20:09:57,494 | INFO | Answer generation input tokens: 2135
2026-10-05 20:10:14,138 | INFO | user prompt: In a MIMIC‑IV trial, how did ViSTA's AUC compare to GPT‑5.6 Sol for AKI?, web query: MIMIC IV AKI comparison AUC
2026-10-05 20:10:25,490 | WARNING | arXiv timeout/no results for query: MIMIC IV AKI comparison AUC
2026-10-05 20:10:26,756 | INFO | user prompt: In a MIMIC‑IV trial, how did ViSTA's AUC compare to GPT‑5.6 Sol for AKI?, web query: MIMIC IV AKI prediction model performance comparison
2026-10-05 20:10:26,757 | INFO | Retry query: MIMIC IV AKI prediction model performance comparison
2026-10-05 20:10:38,177 | WARNING | arXiv timeout/no results for query: MIMIC IV AKI prediction model performance comparison
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.05it/s]
2026-10-05 20:10:38,312 | ERROR | RAG failed: Failed to parse: Host 'MIMIC IV AKI prediction model performance comparison' contains invalid character ' '
2026-10-05 20:10:39,592 | INFO | user prompt: Identify factors hindering hyperspectral video compression, given dataset expansion and method infancy., web query: hyperspectral video compression challenges dataset expansion method infancy
2026-10-05 20:10:50,976 | WARNING | arXiv timeout/no results for query: hyperspectral video compression challenges dataset expansion method infancy
2026-10-05 20:10:52,236 | INFO | user prompt: Identify factors hindering hyperspectral video compression, given dataset expansion and method infancy., web query: hyperspectral video compression challenges dataset limitations method development
2026-10-05 20:10:52,236 | INFO | Retry query: hyperspectral video compression challenges dataset limitations method development
2026-10-05 20:11:03,701 | WARNING | arXiv timeout/no results for query: hyperspectral video compression challenges dataset limitations method development
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]
2026-10-05 20:11:03,834 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-05 20:11:04,932 | INFO | user prompt: Describe LOHA's soft-token compression of past tool obs, preserving agent turns and last K obs., web query: soft token compression agent turns observation preservation
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.81it/s]
2026-10-05 20:11:07,449 | INFO | Answer generation input tokens: 1837
2026-10-05 20:11:23,902 | INFO | user prompt: Contrast APG’s post‑debate verification with passive logging in stopping fabricated consensus., web query: post debate verification consensus fabrication logging
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 60.68it/s]
2026-10-05 20:11:26,713 | INFO | Answer generation input tokens: 1852
2026-10-05 20:11:44,713 | INFO | user prompt: Imagine a VLM on a highres image with contour and shading—why miss the shading?, web query: high resolution image shading analysis
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]
Batches: 100%|██████████| 9/9 [00:00<00:00, 11.70it/s]
2026-10-05 20:12:01,004 | INFO | Answer generation input tokens: 1823
2026-10-05 20:12:06,974 | INFO | user prompt: How does Intent2Tc use LLMs, DT, and RAG to convert traffic intents into tc configs?, web query: LLM traffic intent configuration RAG
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.81it/s]
2026-10-05 20:12:14,841 | INFO | Answer generation input tokens: 1993
2026-10-05 20:12:49,569 | INFO | user prompt: How does ActKV's action‑oriented eviction and confidence‑driven budget reduce KV cache memory yet preserve accuracy?, web query: KV cache optimization accuracy preservation
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]
Batches: 100%|██████████| 16/16 [00:01<00:00, 11.37it/s]
2026-10-05 20:13:00,970 | INFO | Answer generation input tokens: 2184
2026-10-05 20:13:07,686 | INFO | user prompt: Explain how ECO’s postprocessing anchors endpoints, corrects waypoint inconsistencies, and improves feasibility without extra training., web query: postprocessing anchors waypoint feasibility
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.98it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 14.25it/s]
2026-10-05 20:13:12,832 | INFO | Answer generation input tokens: 1822
2026-10-05 20:13:34,697 | INFO | user prompt: Compare H2S’s evidence selection and summarization with standard LLM reasoning for long documents., web query: H2S document reasoning summarization LLM comparison
2026-10-05 20:13:53,080 | WARNING | arXiv timeout/no results for query: H2S document reasoning summarization LLM comparison
2026-10-05 20:13:54,729 | INFO | user prompt: Compare H2S’s evidence selection and summarization with standard LLM reasoning for long documents., web query: Document reasoning mechanisms in LLMs versus H2S for long text summarization
2026-10-05 20:13:54,729 | INFO | Retry query: Document reasoning mechanisms in LLMs versus H2S for long text summarization
2026-10-05 20:14:06,152 | WARNING | arXiv timeout/no results for query: Document reasoning mechanisms in LLMs versus H2S for long text summarization
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]
2026-10-05 20:14:06,288 | ERROR | RAG failed: Failed to parse: Host 'Document reasoning mechanisms in LLMs versus H2S for long text summarization' contains invalid character ' '
2026-10-05 20:14:07,239 | INFO | user prompt: ReVerPi study: how much does projection reduce aggregate logical tokens vs full, specify %?, web query: projection reduction logical tokens aggregate
2026-10-05 20:14:18,624 | WARNING | arXiv timeout/no results for query: projection reduction logical tokens aggregate
2026-10-05 20:14:19,500 | INFO | user prompt: ReVerPi study: how much does projection reduce aggregate logical tokens vs full, specify %?, web query: projection reduction aggregate logical tokens
2026-10-05 20:14:19,501 | INFO | Retry query: projection reduction aggregate logical tokens
2026-10-05 20:14:30,999 | WARNING | arXiv timeout/no results for query: projection reduction aggregate logical tokens
Batches: 100%|██████████| 1/1 [00:00<00:00, 17.09it/s]
2026-10-05 20:14:31,154 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-05 20:14:32,326 | INFO | user prompt: Explain how PoLar's dynamic routing mirrors thalamic routing and quantify its performance over standard pass., web query: dynamic routing thalamic routing performance comparison
2026-10-05 20:14:44,416 | WARNING | arXiv timeout/no results for query: dynamic routing thalamic routing performance comparison
2026-10-05 20:14:45,674 | INFO | user prompt: Explain how PoLar's dynamic routing mirrors thalamic routing and quantify its performance over standard pass., web query: dynamic routing neural network thalamic pathway efficiency comparison
2026-10-05 20:14:45,674 | INFO | Retry query: dynamic routing neural network thalamic pathway efficiency comparison
2026-10-05 20:14:57,158 | WARNING | arXiv timeout/no results for query: dynamic routing neural network thalamic pathway efficiency comparison
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.99it/s]
2026-10-05 20:14:57,276 | ERROR | RAG failed: Failed to parse: Host 'dynamic routing neural network thalamic pathway efficiency comparison' contains invalid character ' '
2026-10-05 20:14:58,387 | INFO | user prompt: Compare MCP's read‑only resource exposure with SDC gateway's policy‑validated dry‑run action affordances., web query: resource exposure policy validation dry run actions
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 16.21it/s]
2026-10-05 20:15:00,490 | INFO | Answer generation input tokens: 1793
2026-10-05 20:15:23,415 | INFO | user prompt: How does mutable transcripts, natural edits, reduce context pollution, shorten chats, and improve LLM quality?, web query: mutable transcripts natural edits context pollution LLM quality
Batches: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 15.91it/s]
2026-10-05 20:15:25,448 | INFO | Answer generation input tokens: 1623
2026-10-05 20:15:42,581 | INFO | user prompt: How does DyMD use TA‑re‑noise sampling and DG‑fake‑score tracking adapt teach‑supervision and critic fitting ev‑stud?, web query: TA-re-noise sampling DG-fake-score tracking teach-supervision critic fitting
2026-10-05 20:15:54,023 | WARNING | arXiv timeout/no results for query: TA-re-noise sampling DG-fake-score tracking teach-supervision critic fitting
2026-10-05 20:15:55,564 | INFO | user prompt: How does DyMD use TA‑re‑noise sampling and DG‑fake‑score tracking adapt teach‑supervision and critic fitting ev‑stud?, web query: DyMD adaptive training noise sampling dynamic gradient tracking supervised learning critic alignment
2026-10-05 20:15:55,564 | INFO | Retry query: DyMD adaptive training noise sampling dynamic gradient tracking supervised learning critic alignment
2026-10-05 20:16:06,946 | WARNING | arXiv timeout/no results for query: DyMD adaptive training noise sampling dynamic gradient tracking supervised learning critic alignment
Batches: 100%|██████████| 1/1 [00:00<00:00, 35.63it/s]

In [36]:
pd.set_option("display.max_colwidth", None)
results = pd.DataFrame(results)
results.head(5)

,golden_id,answer,latency
0,1,"{'answer': None, 'status': 'failed', 'error': 'Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?'}",26.047997
1,2,"{'answer': 'Authors minimize queries and achieve optimal target alignment in black-box generative AI through the development of post-processing algorithms that focus on statistical attribute alignment. These algorithms aim to ensure that the distribution of an attribute of the AI-generated output aligns with a user-specified target. They minimize the expected number of queries to the generator and demonstrate their optimality as the number of requested outputs $ m \to \infty $. The algorithms, such as the Random Demand Coupon (RDC) algorithm, are designed to work within a black-box setting where the user can only query the generative AI model. These post-processing methods complement prompting-based interventions, which may not always be effective due to models not following instructions accurately. The authors also illustrate the effectiveness of their methods through experiments on tasks such as text-to-image generation and geocoded persona generation. URL: https://arxiv.org/pdf/2609.31607', 'status': 'success', 'error': None}",25.567972
2,3,"{'answer': None, 'status': 'failed', 'error': 'Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?'}",25.262339
3,4,"{'answer': None, 'status': 'failed', 'error': 'Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?'}",25.287791
4,5,"{'answer': 'Teachers adapt conversational AI use by balancing repair, differentiation, translation, and navigating tensions related to technology, learners, and instruction. They repair failing technology, differentiate for gaps in learners' readiness, translate abstract AI concepts through familiar stories, and balance children's creative agency with learning goals. Teachers constantly navigate these tensions and their adaptive labor bridge the gap for the successful implementation of the AI tool and curriculum. This adaptive work is supported by structured channels such as daily individual and group reflections. URL: https://arxiv.org/pdf/2609.31569', 'status': 'success', 'error': None}",17.194196

My first run with the golden question resulted in error, since the web queries that were generted by the llm were too specific, and the arxive website did returned no results:

```2026-10-05 18:43:55,370 | INFO | user prompt: How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?, web query: "confidence supervision token reduction 25% accuracy preservation Gemma Qwen Nemotron GPT-OSS"```

I have tried to resolve this error by prompt engineering and adding a retry query generation. If the first web qury has not found any titles, I prompt the llm to generate a new one and also mark the old query as "bad". In case if the second query has not generated anything, I stop retrying. After trying this approach I had 30% of failed test cases. After examining the failed test cases, I came to the conclusion that some of the generated questions from the golden data set are too specific and not suitable for arxive websearch. My solution to this problem is to let the llm answer the question without using the context. However, to restrict a user from using the RAG model for unrealted to its purpose prompts, I will add a classifier model, that would either let the prompt proceed further in the pipline or not. Only AI, CS related topics can be promt, or other topics that are represented in the arxive web-site.

In [25]:
failed = results[
    results["answer"].apply(lambda x: x["status"] == "failed")
]
print(f"Percentage of failed questions: {len(failed) / len(results) * 100}%")

Percentage of failed questions: 30.0%

In [56]:
logs = pd.read_csv("rag_logs.csv")

retry_then_warning = (
    logs["message"].str.contains("Retry", case=False, na=False)
    & logs["level"].shift(-1).eq("WARNING")
)
retry_then_success = (
    logs["message"].str.contains("Retry", case=False, na=False)
    & ~logs["level"].shift(-1).eq("WARNING")
)

print(f"In {retry_then_warning.sum()} test cases prompt retry did not work")
print(f"In {retry_then_success.sum()} test cases prompt retry worked")

In 15 test cases prompt retry did not work
In 1 test cases prompt retry worked

My solution with retrying worked only for one test case.

In [57]:
pd.set_option("display.max_colwidth", None)
golden_df[golden_df["golden_id"].isin(failed["golden_id"])][["question"]].head(3)

                                                                                                  question
0  How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?
2              How does static compact doc alone affect issue resolution in real repos vs. source present?
3    How does OC‑GS refine angles, keep axis, boostPSNR amid uneven rotation, dropped frames, sparse caps?

In [59]:
pd.set_option("display.max_colwidth", None)
answers = results[results["answer"].apply(lambda x: x["answer"] is not None)][["golden_id", "answer"]].copy()

answers["answer"] = answers["answer"].apply(lambda x: x["answer"])

combined = (golden_df[~golden_df["golden_id"]
            .isin(failed["golden_id"])][["golden_id", "question"]]
            .merge(answers,on="golden_id"))

combined[["question", "answer"]].head(3)

,question,answer
0,"How do authors minimize queries, achieve optimal tgt alignment, post‑process, prompting in black‑box generative AI?","Authors minimize queries and achieve optimal target alignment in black-box generative AI through the development of post-processing algorithms that focus on statistical attribute alignment. These algorithms aim to ensure that the distribution of an attribute of the AI-generated output aligns with a user-specified target. They minimize the expected number of queries to the generator and demonstrate their optimality as the number of requested outputs $ m \to \infty $. The algorithms, such as the Random Demand Coupon (RDC) algorithm, are designed to work within a black-box setting where the user can only query the generative AI model. These post-processing methods complement prompting-based interventions, which may not always be effective due to models not following instructions accurately. The authors also illustrate the effectiveness of their methods through experiments on tasks such as text-to-image generation and geocoded persona generation. \n\nURL: https://arxiv.org/pdf/2609.31607"
1,"How do teachers adapt conv. AI use, balancing repair, differentiation, translation, tech, learner, instr. tensions?","Teachers adapt conversational AI use by balancing repair, differentiation, translation, and navigating tensions related to technology, learners, and instruction. They repair failing technology, differentiate for gaps in learners' readiness, translate abstract AI concepts through familiar stories, and balance children's creative agency with learning goals. Teachers constantly navigate these tensions and their adaptive labor bridge the gap for the successful implementation of the AI tool and curriculum. This adaptive work is supported by structured channels such as daily individual and group reflections. \n\nURL: https://arxiv.org/pdf/2609.31569"
2,How does DeepEdu‑v1’s long‑context engine yield TTFT speedup over vLLM in Vietnam AI tutoring?,"DeepEdu-v1’s long-context inference engine achieves a TTFT (Time-to-First-Token) speedup over vLLM by amortizing token selection from per-sub-chunk to per-cluster granularity. This reduces retrieval calls by 7.7× on long-context retrieval, cutting prefill latency (TTFT) by roughly 35% while maintaining or improving task accuracy. In its deployed configuration, DeepEdu achieves a nearly 2× TTFT speedup over standard vLLM serving. \n\nURL: https://arxiv.org/pdf/2609.31568"

In [65]:
print(f"Mean end-to-end latency: {results["latency"].mean():.2f} sec")

Mean end-to-end latency: 24.36 sec