In [18]:
from debugpy.common.log import timestamp_format
from transformers import AutoModelForCausalLM, AutoTokenizer
from IPython.display import display, Markdown
import pandas as pd
import time
from rag_flow import RAGFlow
from eval import Eval
from datetime import datetime

In [19]:
def load_model():
    model_name = "Qwen/Qwen3-8B"
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype="auto",
        device_map="auto",
        local_files_only=True #swith it off to download from hugging face if you don't have it locally
    )
    tokenizer = AutoTokenizer.from_pretrained(model_name, local_files_only=True)
    return {"model": model, "tokenizer": tokenizer}

In [20]:
model_and_tokenizer = load_model()
model = model_and_tokenizer["model"]
tokenizer = model_and_tokenizer["tokenizer"]

Loading weights: 100%|██████████| 399/399 [00:03<00:00, 117.12it/s]

In [21]:
params = {
    "model": model,
    "tokenizer": tokenizer,
    "web_query_max_new_t": 50,
    "titles_limit": 5,
    "top_k_titles": 5,
    "chunk_size": 200,
    "chunk_overlap_fraction": 0.2,
    "top_k_chunks": 5,
    "answer_max_new_t": 500
}


rag = RAGFlow(params)

answer = rag.run("How does retrieval-augmented generation reduce hallucinations in large language models??")

2026-10-06 16:17:47,801 | INFO | user prompt: How does retrieval-augmented generation reduce hallucinations in large language models??, web query: retrieval augmented generation hallucinations large language models
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.54it/s]
Batches: 100%|██████████| 12/12 [00:01<00:00, 11.45it/s]
2026-10-06 16:17:53,077 | INFO | Answer generation input tokens: 2253

In [22]:
answer

{'answer': 'Retrieval-Augmented Generation (RAG) reduces hallucinations in large language models by grounding responses in retrieved evidence from external sources. This allows models to use up-to-date and verifiable information beyond their fixed parameters, thereby mitigating the risk of generating false or misleading information. The context indicates that while RAG significantly reduces hallucinations, reliability remains a concern when the retrieved content is irrelevant, outdated, or misleading, as inaccuracies in retrieval can propagate into the final response.\n\nURL: https://arxiv.org/pdf/2610.01936',
 'status': 'success',
 'error': None,
 'token_usage': 2253,
 'chunks': [{'article_url': 'https://arxiv.org/pdf/2610.01936',
   'title': 'Mapping the RAG Landscape: A Four Axis Taxonomy of Efficiency, Defense, Interactivity, and Reasoning',
   'chunk_index': 108,
   'text': 'In deployment, this leads to outdated retrieval outputs, higher latency, and reduced reliability-problems that be- come especially severe in enterprise, time-sensitive, and mission-critical applications. 5.2 Hallucination and Reliability Issues Although RAG frameworks significantly reduce hallucinations in large language models by grounding responses in retrieved evidence, reliability remains a persistent concern: • Hallucinations still occur when the retrieved content is irrelevant, outdated, or misleading; because generation is conditioned on this context, inaccuracies in retrieval propagate into the final response and can create a false sense of factuality [217, 211, 218]. • Even with rich external sources, incomplete or noisy knowledge bases can lead to erroneous answers, partic- ularly in open-domain settings; LLMs also struggle to interpret subtle nuances or contradictions in retrieved text, sometimes producing overly confident responses that misrepresent the evidence [219, 216]. • Integrating retrieved content fluently and coherently into generated outputs is itself a challenge: misalignment be- tween retrieved evidence and the model’s internal priors can yield unnatural phrasing, semantic inconsistencies, or selective use of evidence that omits key qualifiers [220]. • In cases where user queries extend beyond the scope or coverage of the knowledge base, RAG systems may even underperform relative to purely parametric LLMs, be-'},
  {'article_url': 'https://arxiv.org/pdf/2610.01936',
   'title': 'Mapping the RAG Landscape: A Four Axis Taxonomy of Efficiency, Defense, Interactivity, and Reasoning',
   'chunk_index': 188,
   'text': 'Nikoulina, “Adapting large language models for multi-domain retrieval- augmented-generation,” 2025. 24 [227] S. Rakin, M. A. R. Shibly, Z. M. Hossain, M. M. Akbar, and Z. Khan, “Leveraging the domain adaptation of retrieval augmented generation models for question answering and for hallucination reduction,” in International Conference on Infor- mation Technology-New Generations, pp. 482–493, Springer, 2025. 24 [228] S. Zeng, J. Zhang, P. He, J. Ren, T. Zheng, H. Lu, H. Xu, H. Liu, Y. Xing, and J. Tang, “Mitigating the privacy issues in retrieval-augmented generation (rag) via pure synthetic data,” in Proceedings of the 2025 Conference on Empirical Methods in Natural Language Processing, pp. 24538–24569, 2025. 24 [229] S. Wu, Y. Xiong, Y. Cui, H. Wu, C. Chen, Y. Yuan, L. Huang, X. Liu, T.-W. Kuo, N. Guan, et al., “Retrieval-augmented generation for natural language processing: A survey,” 2024. 24 [230] V. Kanka, Scaling big data: leveraging LLMs for enterprise success. Libertatem Media Private Limited, 2024. 24 [231] M. A. Ferrag, F. Alwahedi, A. Battah, B. Cherif, A. Mechri, N. Tihanyi, T. Bisztray, and M. Debbah, “Generative ai in cybersecurity: A comprehensive review of llm applications and vulnerabilities,” Internet of Things and Cyber-Physical Sys- tems, vol. 5, pp. 1–46, 2025.'},
  {'article_url': 'https://arxiv.org/pdf/2609.30337',
   'title': 'Parameters vs. Context: TRACE Fine-Tuning for Robust Retrieval-Augmented Generation',
   'chunk_index': 3,
   'text': 'incomplete, or incor- rect [3], which may lead to factual hallucinations [4] and un- reliable answers. Retrieval-Augmented Generation (RAG) [5] mitigates this problem by conditioning generation on retrieved documents or knowledge-base content, thereby allowing mod- els to use external evidence beyond their fixed parameters [6], [7]. The central difficulty in RAG is that retrieved context can conflict with the model’s parametric knowledge. In practical retrieval pipelines, external context may be correct, mislead- ing, self-conflicting, or irrelevant [8]. As shown in Fig. 1, conventional RAG prompting becomes unstable when the Wrong Irrelevant Self-Conflict Context Type 90 80 70 60 50 40 30 20 10 0 Exact Match (%) Wrong Irrelevant Self-Conflict Context Type 100 90 80 70 60 50 40 30 20 10 0 (a) On Qwen2.5-7B (b) On Llama3.1-8B -12.46 +21.71 +29.83 +60.91 -2.24 -4.20 +23.07 +29.09 +60.50 -4.10 +4.69 +4.69 Fig. 1. Performance under different knowledge-conflict contexts on ConFiQA- MR, ConFiQA-SC, and ExplainPE. retrieved context is unreliable: incorrect or irrelevant context can mislead the model and even make it perform worse than query-only prompting, while self-conflicting context provides only limited gains. These observations indicate that LLMs do not inherently know when to trust retrieved evidence, when to rely on'},
  {'article_url': 'https://arxiv.org/pdf/2610.01936',
   'title': 'Mapping the RAG Landscape: A Four Axis Taxonomy of Efficiency, Defense, Interactivity, and Reasoning',
   'chunk_index': 1,
   'text': '1 Mapping the RAG Landscape: A Four-Axis Taxonomy of Efficiency, Defense, Interactivity, and Reasoning Meghana Sunil1†, Shravya V1†, Shravan Venkatraman2, Joe Dhanith P R1∗ Abstract—Large Language Models (LLMs) have demonstrated remarkable fluency across many tasks but remain limited by their static, parameter-bound knowledge and their susceptibility to hallucinating information. Retrieval-Augmented Generation (RAG) addresses these issues by incorporating external retrieval into the generation process, grounding model outputs in verifiable and up-to-date sources. While prior surveys primarily focus on core RAG architectures and standard pipelines, recent research explores broader challenges and capabilities that extend beyond these foundational designs. This survey provides a consolidated and structured examination of contemporary RAG developments, organizing the field into a four-axis taxonomy: improving retrieval efficiency, strengthening robustness and security, supporting user-driven and interactive workflows, and enabling multi-step or complex reasoning. We formalize key components of the RAG framework and review methods spanning dense and sparse retrieval, fusion strategies, embedding optimizations, and reinforcement-learning–based retrieval policies, highlighting how these advances influence practical deployment and system design. We also synthesize evaluation practices, domain-specific applications, and architectural variants such as Naive, Advanced, and Modular RAG. Finally, we outline persistent challenges related to retrieval quality, reliability, domain adaptation, scalability, and explainability, and'},
  {'article_url': 'https://arxiv.org/pdf/2610.01936',
   'title': 'Mapping the RAG Landscape: A Four Axis Taxonomy of Efficiency, Defense, Interactivity, and Reasoning',
   'chunk_index': 162,
   'text': 'and Z. Sun, “Halueval-wild: Evaluating hal- lucinations of language models in the wild,” arXiv preprint arXiv:2403.04307, 2024. 12 [115] B. He, N. Chen, X. He, L. Yan, Z. Wei, J. Luo, and Z.-H. Ling, “Retrieving, rethinking and revising: The chain-of-verification can improve retrieval augmented generation,” in Findings of the Association for Computational Linguistics: EMNLP 2024, pp. 10371–10393, 2024. 12 [116] A. C. Stickland, S. Sengupta, J. Krone, S. Mansour, and H. He, “Robustification of multilingual language models to real-world noise in crosslingual zero-shot settings with robust contrastive pretraining,” in Proceedings of the 17th Conference of the Euro- pean Chapter of the Association for Computational Linguistics, pp. 1375–1391, 2023. 12 [117] R. Ren, Y. Wang, Y. Qu, W. X. Zhao, J. Liu, H. Wu, J.-R. Wen, and H. Wang, “Investigating the factual knowledge boundary of large language models with retrieval augmentation,” in Pro- ceedings of the 31st International Conference on Computational Linguistics, pp. 3697–3715, 2025. 12 [118] L. Zeng, R. Gupta, D. Motwani, D. Yang, and Y. Zhang, “Worse than zero-shot? a fact-checking dataset for evaluating the robustness of rag against misleading retrievals,” 2025. 12 [119] Y. Hui, Y. Lu, and H. Zhang, “Uda: A benchmark suite for re- trieval augmented'}]}

## To do:
- ~~generate ground truth~~
- ~~test and record the results~~
- download 1 -2 more models and test the same flow with them. Chose the one that performed best
- With best model, fine-tune the system:
    - test different numbers of searched titles
    - test different number of downloaded articles
    - try different chunk sizes
    - try different number of top k in the chunk ranker
    - try a set of promot augmentation.
- modify the script to record the token usage
- add llm call to classify questions
- add general answers, no context

In [23]:
sys_evaluation_df = {
    "mean_latency": "",
    "mean_token_usage":"",
    "context_recall":"",
    "context_precision":"",
    "mean_faithfulness":""
}

In [24]:
timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
golden_df = pd.read_csv(f"golden_dataset.csv")

In [25]:
results = []

for _, row in golden_df.iterrows():
    golden_id = row["golden_id"]
    question = row["question"]
    start = time.perf_counter()
    answer = rag.run(question)
    latency = time.perf_counter() - start
    results.append({
        "golden_id": golden_id,
        "answer": answer,
        "latency": latency
    })

evaluation_df = pd.DataFrame(results)
timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
evaluation_df.to_csv(f"test_run_output_{timestamp}.csv")

2026-10-06 16:18:07,664 | INFO | user prompt: How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?, web query: confidence supervision token reduction model efficiency
2026-10-06 16:18:20,344 | WARNING | arXiv timeout/no results for query: confidence supervision token reduction model efficiency
2026-10-06 16:18:21,314 | INFO | user prompt: How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?, web query: confidence supervision token reduction model efficiency
2026-10-06 16:18:21,314 | INFO | Retry query: confidence supervision token reduction model efficiency
2026-10-06 16:18:34,291 | WARNING | arXiv timeout/no results for query: confidence supervision token reduction model efficiency
Batches: 100%|██████████| 1/1 [00:00<00:00, 33.17it/s]
2026-10-06 16:18:34,421 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:18:35,444 | INFO | user prompt: How do authors minimize queries, achieve optimal tgt alignment, post‑process, prompting in black‑box generative AI?, web query: black box generative AI alignment
Batches: 100%|██████████| 1/1 [00:00<00:00, 39.01it/s]
Batches: 100%|██████████| 13/13 [00:01<00:00, 11.34it/s]
2026-10-06 16:18:44,561 | INFO | Answer generation input tokens: 1788
2026-10-06 16:19:07,717 | INFO | user prompt: How does static compact doc alone affect issue resolution in real repos vs. source present?, web query: static doc issue resolution source presence
2026-10-06 16:19:19,115 | WARNING | arXiv timeout/no results for query: static doc issue resolution source presence
2026-10-06 16:19:20,232 | INFO | user prompt: How does static compact doc alone affect issue resolution in real repos vs. source present?, web query: static documentation impact on issue resolution in software repositories
2026-10-06 16:19:20,233 | INFO | Retry query: static documentation impact on issue resolution in software repositories
2026-10-06 16:19:31,628 | WARNING | arXiv timeout/no results for query: static documentation impact on issue resolution in software repositories
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.79it/s]
2026-10-06 16:19:31,749 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:19:32,842 | INFO | user prompt: How does OC‑GS refine angles, keep axis, boostPSNR amid uneven rotation, dropped frames, sparse caps?, web query: angle refinement rotation stability PSNR enhancement
2026-10-06 16:19:44,218 | WARNING | arXiv timeout/no results for query: angle refinement rotation stability PSNR enhancement
2026-10-06 16:19:45,525 | INFO | user prompt: How does OC‑GS refine angles, keep axis, boostPSNR amid uneven rotation, dropped frames, sparse caps?, web query: angle refinement stability PSNR improvement under rotation and missing data
2026-10-06 16:19:45,525 | INFO | Retry query: angle refinement stability PSNR improvement under rotation and missing data
2026-10-06 16:19:56,964 | WARNING | arXiv timeout/no results for query: angle refinement stability PSNR improvement under rotation and missing data
Batches: 100%|██████████| 1/1 [00:00<00:00, 46.32it/s]
2026-10-06 16:19:57,075 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:19:57,977 | INFO | user prompt: How do teachers adapt conv. AI use, balancing repair, differentiation, translation, tech, learner, instr. tensions?, web query: AI adaptation instructional tensions
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.13it/s]
Batches: 100%|██████████| 5/5 [00:00<00:00, 12.46it/s]
2026-10-06 16:20:01,218 | INFO | Answer generation input tokens: 1776
2026-10-06 16:20:15,901 | INFO | user prompt: How does DeepEdu‑v1’s long‑context engine yield TTFT speedup over vLLM in Vietnam AI tutoring?, web query: long context engine TTFT speedup AI tutoring
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.36it/s]
Batches: 100%|██████████| 4/4 [00:00<00:00, 13.09it/s]
2026-10-06 16:20:18,051 | INFO | Answer generation input tokens: 1990
2026-10-06 16:20:32,855 | INFO | user prompt: Imagine 30 LLMs on a disjunctive task; how does scaling improve accuracy?, web query: Large language models disjunctive task scaling accuracy
2026-10-06 16:20:44,272 | WARNING | arXiv timeout/no results for query: Large language models disjunctive task scaling accuracy
2026-10-06 16:20:45,732 | INFO | user prompt: Imagine 30 LLMs on a disjunctive task; how does scaling improve accuracy?, web query: Task scaling effects on model accuracy in disjunctive problem solving
2026-10-06 16:20:45,733 | INFO | Retry query: Task scaling effects on model accuracy in disjunctive problem solving
2026-10-06 16:20:57,143 | WARNING | arXiv timeout/no results for query: Task scaling effects on model accuracy in disjunctive problem solving
Batches: 100%|██████████| 1/1 [00:00<00:00, 43.48it/s]
2026-10-06 16:20:57,264 | ERROR | RAG failed: Failed to parse: Host 'Task scaling effects on model accuracy in disjunctive problem solving' contains invalid character ' '
2026-10-06 16:20:58,496 | INFO | user prompt: Illustrate how flow‑matching derives neural representational dissimilarity to quantify response distribution differences., web query: flow matching representational dissimilarity response distribution
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.85it/s]
Batches: 100%|██████████| 4/4 [00:00<00:00, 13.08it/s]
2026-10-06 16:21:03,420 | INFO | Answer generation input tokens: 1856
2026-10-06 16:21:28,054 | INFO | user prompt: If conflict detection accuracy is 98.6%, what percent of inputs does Touchstone elevate?, web query: Touchstone conflict detection accuracy inputs
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.82it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 16.14it/s]
2026-10-06 16:21:29,906 | INFO | Answer generation input tokens: 1915
2026-10-06 16:21:38,137 | INFO | user prompt: Explain RVA's raw‑supervision weight assignment appearance reliab., degr. risk, geom. util., and reactivating suppressed frames., web query: raw supervision weight assignment reliability degradation geometry utilization reactivation
2026-10-06 16:21:49,586 | WARNING | arXiv timeout/no results for query: raw supervision weight assignment reliability degradation geometry utilization reactivation
2026-10-06 16:21:50,885 | INFO | user prompt: Explain RVA's raw‑supervision weight assignment appearance reliab., degr. risk, geom. util., and reactivating suppressed frames., web query: raw supervision weight assignment reliability degradation geometric utilization frame reactivation
2026-10-06 16:21:50,886 | INFO | Retry query: raw supervision weight assignment reliability degradation geometric utilization frame reactivation
Batches: 100%|██████████| 1/1 [00:00<00:00, 52.77it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 15.41it/s]
2026-10-06 16:21:53,484 | INFO | Answer generation input tokens: 1899
2026-10-06 16:22:12,916 | INFO | user prompt: Compare LLM performance gaps between Haitian Creole and French across cultural awareness dimensions., web query: LLM performance cultural awareness Haitian Creole French
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.16it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 14.43it/s]
2026-10-06 16:22:14,702 | INFO | Answer generation input tokens: 1682
2026-10-06 16:22:39,700 | INFO | user prompt: How do prompt‑minimization techniques reduce inference latency in LLMs?, web query: prompt minimization inference latency LLMs
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.83it/s]
Batches: 100%|██████████| 11/11 [00:00<00:00, 11.54it/s]
2026-10-06 16:22:45,587 | INFO | Answer generation input tokens: 1905
2026-10-06 16:22:57,260 | INFO | user prompt: Describe the types of uncertainty outputs and how they support selective prediction., web query: Uncertainty quantification selective prediction
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.17it/s]
Batches: 100%|██████████| 25/25 [00:02<00:00, 11.56it/s]
2026-10-06 16:23:08,049 | INFO | Answer generation input tokens: 2004
2026-10-06 16:23:25,121 | INFO | user prompt: How do generative AI's epistemic sites, governing logics, mechanisms reshape cultural infrastructures via indexicality shift?, web query: generative AI epistemic sites indexicality cultural infrastructure
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 60.12it/s]
2026-10-06 16:23:27,486 | INFO | Answer generation input tokens: 1770
2026-10-06 16:23:54,641 | INFO | user prompt: Which game envs are in Kaggle Game Arena, and what info types do they cover?, web query: kaggle game arena environments information types
2026-10-06 16:24:06,079 | WARNING | arXiv timeout/no results for query: kaggle game arena environments information types
2026-10-06 16:24:07,193 | INFO | user prompt: Which game envs are in Kaggle Game Arena, and what info types do they cover?, web query: kaggle game arena environments information types
2026-10-06 16:24:07,194 | INFO | Retry query: kaggle game arena environments information types
2026-10-06 16:24:19,846 | WARNING | arXiv timeout/no results for query: kaggle game arena environments information types
Batches: 100%|██████████| 1/1 [00:00<00:00, 63.69it/s]
2026-10-06 16:24:19,955 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:24:21,142 | INFO | user prompt: Which LLM preferences (price, quality, brand) does PriceBench recover from booking choices?, web query: LLM preferences booking choices PriceBench
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.28it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.46it/s]
2026-10-06 16:24:24,830 | INFO | Answer generation input tokens: 1885
2026-10-06 16:24:34,387 | INFO | user prompt: Contrast federated learning with local models and UA‑FedAvg vs FedAvg in infant movement analysis., web query: Federated learning infant movement analysis UA‑FedAvg FedAvg
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.11it/s]
Batches: 100%|██████████| 2/2 [00:00<00:00, 15.19it/s]
2026-10-06 16:24:37,381 | INFO | Answer generation input tokens: 1711
2026-10-06 16:24:56,447 | INFO | user prompt: How does SeLATM's segment‑level generation and agentic feedback cut LLM resources yet preserve topic modeling?, web query: segment level generation agentic feedback topic modeling
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.55it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.74it/s]
2026-10-06 16:24:58,459 | INFO | Answer generation input tokens: 1939
2026-10-06 16:25:12,410 | INFO | user prompt: Which two corruption‑detection signals are compared, and which ds are used in FL?, web query: corruption detection signals federated learning datasets
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 53.35it/s]
2026-10-06 16:25:16,203 | INFO | Answer generation input tokens: 1859
2026-10-06 16:25:28,983 | INFO | user prompt: How does LoRA SFT alter correct‑image accuracy, visual‑benefit events, and image sensitivity in Qwen2.5‑VL‑3B post‑training?, web query: LoRA fine-tuning image accuracy visual sensitivity
Batches: 100%|██████████| 1/1 [00:00<00:00, 40.27it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.79it/s]
2026-10-06 16:25:32,678 | INFO | Answer generation input tokens: 2135
2026-10-06 16:25:51,118 | INFO | user prompt: In a MIMIC‑IV trial, how did ViSTA's AUC compare to GPT‑5.6 Sol for AKI?, web query: MIMIC IV AKI AUC comparison
2026-10-06 16:26:04,458 | WARNING | arXiv timeout/no results for query: MIMIC IV AKI AUC comparison
2026-10-06 16:26:05,697 | INFO | user prompt: In a MIMIC‑IV trial, how did ViSTA's AUC compare to GPT‑5.6 Sol for AKI?, web query: MIMIC IV AKI prediction model performance comparison
2026-10-06 16:26:05,698 | INFO | Retry query: MIMIC IV AKI prediction model performance comparison
2026-10-06 16:26:17,091 | WARNING | arXiv timeout/no results for query: MIMIC IV AKI prediction model performance comparison
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.28it/s]
2026-10-06 16:26:17,212 | ERROR | RAG failed: Failed to parse: Host 'MIMIC IV AKI prediction model performance comparison' contains invalid character ' '
2026-10-06 16:26:18,488 | INFO | user prompt: Identify factors hindering hyperspectral video compression, given dataset expansion and method infancy., web query: hyperspectral video compression challenges dataset expansion method infancy
2026-10-06 16:26:30,168 | WARNING | arXiv timeout/no results for query: hyperspectral video compression challenges dataset expansion method infancy
2026-10-06 16:26:31,430 | INFO | user prompt: Identify factors hindering hyperspectral video compression, given dataset expansion and method infancy., web query: hyperspectral video compression challenges dataset limitations method development
2026-10-06 16:26:31,430 | INFO | Retry query: hyperspectral video compression challenges dataset limitations method development
2026-10-06 16:26:44,444 | WARNING | arXiv timeout/no results for query: hyperspectral video compression challenges dataset limitations method development
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.67it/s]
2026-10-06 16:26:44,562 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:26:45,661 | INFO | user prompt: Describe LOHA's soft-token compression of past tool obs, preserving agent turns and last K obs., web query: soft token compression agent turns observation preservation
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.95it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 13.36it/s]
2026-10-06 16:26:48,417 | INFO | Answer generation input tokens: 1837
2026-10-06 16:27:01,520 | INFO | user prompt: Contrast APG’s post‑debate verification with passive logging in stopping fabricated consensus., web query: post debate verification consensus fabrication logging
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 51.53it/s]
2026-10-06 16:27:04,915 | INFO | Answer generation input tokens: 1852
2026-10-06 16:27:23,310 | INFO | user prompt: Imagine a VLM on a highres image with contour and shading—why miss the shading?, web query: high resolution image shading contour analysis
2026-10-06 16:27:36,112 | WARNING | arXiv timeout/no results for query: high resolution image shading contour analysis
2026-10-06 16:27:37,155 | INFO | user prompt: Imagine a VLM on a highres image with contour and shading—why miss the shading?, web query: high resolution image analysis contour shading interpretation
2026-10-06 16:27:37,156 | INFO | Retry query: high resolution image analysis contour shading interpretation
2026-10-06 16:27:48,515 | WARNING | arXiv timeout/no results for query: high resolution image analysis contour shading interpretation
Batches: 100%|██████████| 1/1 [00:00<00:00, 44.78it/s]
2026-10-06 16:27:48,636 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:27:49,603 | INFO | user prompt: How does Intent2Tc use LLMs, DT, and RAG to convert traffic intents into tc configs?, web query: LLM traffic intent configuration
Batches: 100%|██████████| 1/1 [00:00<00:00, 37.63it/s]
Batches: 100%|██████████| 8/8 [00:00<00:00, 11.63it/s]
2026-10-06 16:27:54,527 | INFO | Answer generation input tokens: 1993
2026-10-06 16:28:33,251 | INFO | user prompt: How does ActKV's action‑oriented eviction and confidence‑driven budget reduce KV cache memory yet preserve accuracy?, web query: KV cache optimization accuracy preservation
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.95it/s]
Batches: 100%|██████████| 16/16 [00:01<00:00, 11.48it/s]
2026-10-06 16:28:38,410 | INFO | Answer generation input tokens: 2184
2026-10-06 16:28:45,237 | INFO | user prompt: Explain how ECO’s postprocessing anchors endpoints, corrects waypoint inconsistencies, and improves feasibility without extra training., web query: postprocessing anchors waypoint consistency feasibility improvement
2026-10-06 16:28:56,680 | WARNING | arXiv timeout/no results for query: postprocessing anchors waypoint consistency feasibility improvement
2026-10-06 16:28:57,730 | INFO | user prompt: Explain how ECO’s postprocessing anchors endpoints, corrects waypoint inconsistencies, and improves feasibility without extra training., web query: postprocessing optimization trajectory consistency feasibility improvement
2026-10-06 16:28:57,731 | INFO | Retry query: postprocessing optimization trajectory consistency feasibility improvement
2026-10-06 16:29:09,482 | WARNING | arXiv timeout/no results for query: postprocessing optimization trajectory consistency feasibility improvement
Batches: 100%|██████████| 1/1 [00:00<00:00, 39.50it/s]
2026-10-06 16:29:09,607 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:29:10,882 | INFO | user prompt: Compare H2S’s evidence selection and summarization with standard LLM reasoning for long documents., web query: H2S document reasoning summarization LLM comparison
2026-10-06 16:29:23,837 | WARNING | arXiv timeout/no results for query: H2S document reasoning summarization LLM comparison
2026-10-06 16:29:25,542 | INFO | user prompt: Compare H2S’s evidence selection and summarization with standard LLM reasoning for long documents., web query: Document reasoning mechanisms in LLMs versus H2S evidence selection and summarization strategies
2026-10-06 16:29:25,543 | INFO | Retry query: Document reasoning mechanisms in LLMs versus H2S evidence selection and summarization strategies
2026-10-06 16:29:37,645 | WARNING | arXiv timeout/no results for query: Document reasoning mechanisms in LLMs versus H2S evidence selection and summarization strategies
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.48it/s]
2026-10-06 16:29:37,768 | ERROR | RAG failed: Failed to parse: Host 'Document reasoning mechanisms in LLMs versus H2S evidence selection and summarization strategies' contains invalid character ' '
2026-10-06 16:29:38,714 | INFO | user prompt: ReVerPi study: how much does projection reduce aggregate logical tokens vs full, specify %?, web query: projection reduction logical tokens aggregation
2026-10-06 16:29:50,415 | WARNING | arXiv timeout/no results for query: projection reduction logical tokens aggregation
2026-10-06 16:29:51,288 | INFO | user prompt: ReVerPi study: how much does projection reduce aggregate logical tokens vs full, specify %?, web query: projection reduction logical token aggregation
2026-10-06 16:29:51,288 | INFO | Retry query: projection reduction logical token aggregation
2026-10-06 16:30:02,799 | WARNING | arXiv timeout/no results for query: projection reduction logical token aggregation
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.34it/s]
2026-10-06 16:30:02,927 | ERROR | RAG failed: Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?
2026-10-06 16:30:04,090 | INFO | user prompt: Explain how PoLar's dynamic routing mirrors thalamic routing and quantify its performance over standard pass., web query: dynamic routing thalamic routing performance comparison
2026-10-06 16:30:17,048 | WARNING | arXiv timeout/no results for query: dynamic routing thalamic routing performance comparison
2026-10-06 16:30:18,348 | INFO | user prompt: Explain how PoLar's dynamic routing mirrors thalamic routing and quantify its performance over standard pass., web query: Dynamic routing neural network thalamic circuit mechanism performance comparison
2026-10-06 16:30:18,349 | INFO | Retry query: Dynamic routing neural network thalamic circuit mechanism performance comparison
2026-10-06 16:30:31,410 | WARNING | arXiv timeout/no results for query: Dynamic routing neural network thalamic circuit mechanism performance comparison
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.45it/s]

In [37]:
# pd.set_option("display.max_colwidth", None)
results = pd.DataFrame(results)
results.head(5)

   golden_id  \
0          1
1          2
2          3
3          4
4          5

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        answer  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {'answer': None, 'status': 'failed', 'error': 'Invalid URL 'timeout': No scheme supplied. Perhaps you meant https://timeout?'}
1  {'answer': 'Authors minimize queries and achieve optimal target alignment in black-box generative AI by developing post-processing algorithms that reduce the expected number of queries to the generator. These algorithms ensure that the joint attribute distribution of the generated outputs aligns as closely as possible with a user-specified target distribution. They demonstrate the optimality of these algorithms as the number of requested outputs $ m \to \infty $. Additionally, they introduce the Random Demand Coupon Collector (RDC) algorithm, which is a source-rate-free method that samples a target attribute sequence and then M-samples from the generator. The authors also highlight that post-processing methods, such as RDC and TA-RDC, can substantially improve alignment with the target attribute distribution even when input-side interventions like prompting fail.

The authors compare their post-processing methods with prompting-based interventions, showing that while prompting can be used to request specific attributes, it is not always effective due to models not following instructions. Post-processing methods, on the other hand, provide a more reliable way to align the generated outputs with the desired target distribution.

The experiments conducted on tasks such as text-to-image generation and geocoded persona generation demonstrate the effectiveness of these post-processing algorithms in improving statistical attribute alignment.


My first run with the golden question resulted in error, since the web queries that were generted by the llm were too specific, and the arxive website did returned no results:

```2026-10-05 18:43:55,370 | INFO | user prompt: How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?, web query: "confidence supervision token reduction 25% accuracy preservation Gemma Qwen Nemotron GPT-OSS"```

I have tried to resolve this error by prompt engineering and adding a retry query generation. If the first web qury has not found any titles, I prompt the llm to generate a new one and also mark the old query as "bad". In case if the second query has not generated anything, I stop retrying. After trying this approach I had 30% of failed test cases. After examining the failed test cases, I came to the conclusion that some of the generated questions from the golden data set are too specific and not suitable for arxive websearch. My solution to this problem is to let the llm answer the question without using the context. However, to restrict a user from using the RAG model for unrealted to its purpose prompts, I will add a classifier model, that would either let the prompt proceed further in the pipline or not. Only AI, CS related topics can be promt, or other topics that are represented in the arxive web-site.

In [27]:
failed = results[
    results["answer"].apply(lambda x: x["status"] == "failed")
]
print(f"Percentage of failed questions: {len(failed) / len(results) * 100}%")

Percentage of failed questions: 34.0%

In [28]:
results

    golden_id  \
0           1
1           2
2           3
3           4
4           5
5           6
6           7
7           8
8           9
9          10
10         11
11         12
12         13
13         14
14         15
15         16
16         17
17         18
18         19
19         20
20         21
21         22
22         23
23         24
24         25
25         26
26         27
27         28
28         29
29         30
30         31
31         32
32         33
33         34
34         35
35         36
36         37
37         38
38         39
39         40
40         41
41         42
42         43
43         44
44         45
45         46
46         47
47         48
48         49
49         50

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            answer  \

In [29]:
logs = pd.read_csv("rag_logs.csv")

retry_then_warning = (
    logs["message"].str.contains("Retry", case=False, na=False)
    & logs["level"].shift(-1).eq("WARNING")
)
retry_then_success = (
    logs["message"].str.contains("Retry", case=False, na=False)
    & ~logs["level"].shift(-1).eq("WARNING")
)

print(f"In {retry_then_warning.sum()} test cases prompt retry did not work")
print(f"In {retry_then_success.sum()} test cases prompt retry worked")

In 15 test cases prompt retry did not work
In 1 test cases prompt retry worked

My solution with retrying worked only for one test case.

In [39]:
# pd.set_option("display.max_colwidth", None)
golden_df[golden_df["golden_id"].isin(failed["golden_id"])][["question"]].head(3)

                                                                                                  question
0  How does confidence supervision cut tokens by 25% and preserve accuracy Gemma, Qwen, Nemotron, GPT‑OSS?
2              How does static compact doc alone affect issue resolution in real repos vs. source present?
3    How does OC‑GS refine angles, keep axis, boostPSNR amid uneven rotation, dropped frames, sparse caps?

In [31]:
# pd.set_option("display.max_colwidth", None)
answers = results[results["answer"].apply(lambda x: x["answer"] is not None)][["golden_id", "answer"]].copy()

answers["answer"] = answers["answer"].apply(lambda x: x["answer"])

combined = (golden_df[~golden_df["golden_id"]
            .isin(failed["golden_id"])][["golden_id", "question"]]
            .merge(answers,on="golden_id"))

combined[["question", "answer"]].head(3)

,question,answer
0,"How do authors minimize queries, achieve optimal tgt alignment, post‑process, prompting in black‑box generative AI?","Authors minimize queries and achieve optimal target alignment in black-box generative AI by developing post-processing algorithms that reduce the expected number of queries to the generator. These algorithms ensure that the joint attribute distribution of the generated outputs aligns as closely as possible with a user-specified target distribution. They demonstrate the optimality of these algorithms as the number of requested outputs $ m \to \infty $. Additionally, they introduce the Random Demand Coupon Collector (RDC) algorithm, which is a source-rate-free method that samples a target attribute sequence and then M-samples from the generator. The authors also highlight that post-processing methods, such as RDC and TA-RDC, can substantially improve alignment with the target attribute distribution even when input-side interventions like prompting fail. \n\nThe authors compare their post-processing methods with prompting-based interventions, showing that while prompting can be used to request specific attributes, it is not always effective due to models not following instructions. Post-processing methods, on the other hand, provide a more reliable way to align the generated outputs with the desired target distribution. \n\nThe experiments conducted on tasks such as text-to-image generation and geocoded persona generation demonstrate the effectiveness of these post-processing algorithms in improving statistical attribute alignment. \n\nURL: https://arxiv.org/pdf/2609.31607"
1,"How do teachers adapt conv. AI use, balancing repair, differentiation, translation, tech, learner, instr. tensions?","Teachers adapt conversational AI use by performing four modes of adaptive practices: repair, differentiation, translation, and balancing. These practices occur at the intersection of three tensions: technology, learners, and instruction. Teachers repair failing technology, differentiate for gaps in learners’ readiness, translate abstract AI concepts through familiar stories, and balance children’s creative agency with learning goals. The implementation of AI tools and curricula for elementary levels should be designed for teacher improvisation, including structured channels for reflection and design-iteration-reflection loops. This helps teachers navigate tensions and adapt the curriculum to fit their students’ needs.\n\nURL: https://arxiv.org/pdf/2609.31569"
2,How does DeepEdu‑v1’s long‑context engine yield TTFT speedup over vLLM in Vietnam AI tutoring?,"DeepEdu-v1’s long-context inference engine yields a TTFT (Time-to-First-Token) speedup over vLLM by amortizing token selection from per-sub-chunk to per-cluster granularity. This reduces retrieval calls by 7.7× on long-context retrieval, cutting prefill latency (TTFT) by roughly 35% while maintaining or improving task accuracy. In its deployed configuration, DeepEdu achieves a nearly 2× TTFT speedup over standard vLLM serving.\n\nURL: https://arxiv.org/pdf/2609.31568"

In [32]:
print(f"Mean end-to-end latency: {results["latency"].mean():.2f} sec")
print(f"{len(combined)} answers have been generated")

Mean end-to-end latency: 24.55 sec
33 answers have been generated

I will run the relevancy evaluation test for those 35 successfully generated answers.

In [33]:
timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
combined.to_csv(f"questions-answers_{timestamp}.csv")

In [34]:
ques_ans_df = pd.read_csv("questions-answers.csv")
eval = Eval()
r = eval.answer_relevancy(ques_ans_df, 0.5)

/Users/vilya/Desktop/capstone_project/.venv/lib/python3.14/site-packages/rich/live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

2026-10-06 16:39:23,233 | INFO | HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"

KeyboardInterrupt:

2026-10-06 16:39:38,946 | INFO | HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"

In [ ]:
timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
relevancy = pd.DataFrame(r)
relevancy.to_csv(f"relevancy_eval_results_{timestamp}.csv")

In [ ]:
pass_rate = (relevancy["score"] > 0.5).mean()
print(f"Relevancy pass rate: {pass_rate:.2%}")

In [ ]:
# f = eval.faithfullness(ques_ans_df)

In [ ]:
from datetime import datetime

## Evaluation
### System level:
1. Token usage per prompt.
2. [x] End-to-End Latency
3. Mean Answer Relevance — measures whether the generated answer is relevant to the expected answer. I will calculate the cosine similarity between the generated answer and the expected answer. Answers with a similarity score greater than 0.5 will be classified as relevant (`True`), while answers with a score of 0.5 or lower will be classified as irrelevant (`False`). I will then calculate the proportion of relevant answers among all generated answers.
4. Mean Context Precision — measures how much of the retrieved context is relevant to answering the question. It evaluates the proportion of relevant retrieved chunks among all retrieved chunks.
5. Faithfulness — measures whether the generated answer is supported by the retrieved context and does not contain unsupported claims (hallucinations). I will use an LLM-as-a-judge to evaluate faithfulness.
### Retrieval level
- Context precision/ recall @ k
- Mean reciprocal rank (MRR)
- Normalized Discounted Cumulative Gain (NDCG)  how well top-k is sorted